name: Ruby

on: [push, pull_request]

jobs:
  build:
    name: Ruby
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install sqlite
        run: sudo apt-get install libsqlite3-dev
      - name: Install yarn
        run: | 
          sudo apt install yarn
          yarn install
      - name: Run bundle install
        working-directory: ${{env.api-dir}}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: |
          bundler exec rails db:create
          bundler exec rails db:migrate
      - name: Build and test with rspec
        env:
          RAILS_ENV: test
        run: bundle exec rspec spec
      - name: Simplecov Report
        uses: aki77/simplecov-report-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
